ctkrecentchooserutils: Fix build warnings
Fixes the warnings:

 ctkrecentchooserutils.c: In function 'sort_recent_items_mru':
 ctkrecentchooserutils.c:302:43: error: arithmetic on pointer to an incomplete type
   302 |   return ctk_recent_info_get_modified (b) - ctk_recent_info_get_modified (a);
       |                                           ^
 ctkrecentchooserutils.c: In function 'sort_recent_items_lru':
 ctkrecentchooserutils.c:312:49: error: arithmetic on pointer to an incomplete type
   312 |   return -1 * (ctk_recent_info_get_modified (b) - ctk_recent_info_get_modified (a));
       |                                                 ^

since the commit:
https://github.com/cafe-desktop/ctk/commit/33165914e3d0ffc1dd3be143fec03552e5531a47